# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0009_notification_is_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='author',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_anon',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_system',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_view',
        ),
        migrations.AddField(
            model_name='action',
            name='important',
            field=models.BooleanField(default=True, verbose_name='Важное сообщение'),
        ),
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(default='/media/notifications/standart.png', max_length=256, verbose_name='Ссылка на иконку'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(1, 'Обычное текстовое уведомление'), (2, 'Получение предмета из подаркопульты'), (3, 'Получение нового достижения'), (4, 'Системное уведомление')], default=1, verbose_name='Тип уведомления'),
        ),
        migrations.AddField(
            model_name='notification',
            name='view',
            field=models.BooleanField(default=False, verbose_name='Уведомление просмотрено'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время получения'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(max_length=256, verbose_name='Текст уведомления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Заголовок уведомления'),
        ),
    ]
