# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0010_auto_20160403_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ссылка'),
        ),
    ]
