# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0011_notification_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='icon',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(1, 'Обычное текстовое уведомление'), (2, 'Получение предмета из подаркопульты'), (3, 'Получение нового достижения'), (4, 'Системное уведомление'), (5, 'Уведомление о новом уровне'), (6, 'Уведомление о мероприятии'), (7, 'Уведоление для beta-пользователей')], default=1, verbose_name='Тип уведомления'),
        ),
    ]
