# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0012_auto_20160403_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='type',
            field=models.IntegerField(choices=[(0, 'Запись'), (1, 'Достижение'), (2, 'Случайный бонус'), (3, 'Продажа'), (4, 'Мероприятие'), (5, 'Опрос'), (6, 'Расписание'), (7, 'Заметки')], default=0, verbose_name='Тип записи'),
        ),
        migrations.AddField(
            model_name='action',
            name='value',
            field=models.TextField(blank=True, null=True, verbose_name='Значение'),
        ),
    ]
