# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 11:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название фона')),
                ('icon', models.ImageField(default='img/2015/08/04/ufo.jpg', upload_to='background/%Y/%m/%d/', verbose_name='Фон')),
                ('price_low', models.IntegerField(verbose_name='Цена за барахло')),
                ('price_med', models.IntegerField(verbose_name='Цена за качественную вещь')),
                ('price_high', models.IntegerField(verbose_name='Цена за дорогую вещь')),
            ],
        ),
        migrations.CreateModel(
            name='Catapult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название раздачи')),
                ('view', models.BooleanField(default=False, verbose_name='Получено')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название фона')),
                ('icon', models.ImageField(default='img/2015/08/04/ufo.jpg', upload_to='background/%Y/%m/%d/', verbose_name='Фон')),
                ('price_low', models.IntegerField(verbose_name='Цена за барахло')),
                ('price_med', models.IntegerField(verbose_name='Цена за качественную вещь')),
                ('price_high', models.IntegerField(verbose_name='Цена за дорогую вещь')),
                ('no_sold', models.BooleanField(default=False, verbose_name='Не для продажи')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название коллекции')),
                ('items', models.ManyToManyField(to='inventory.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Smile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название смайлика')),
                ('symbol', models.CharField(max_length=32, verbose_name='Обозначение смайлика')),
                ('icon', models.ImageField(default='img/2015/08/04/ufo.jpg', upload_to='smiles/%Y/%m/%d/', verbose_name='Иконка смайлика')),
            ],
        ),
        migrations.CreateModel(
            name='SmileCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название коллекции')),
                ('price_low', models.IntegerField(verbose_name='Цена за барахло')),
                ('price_med', models.IntegerField(verbose_name='Цена за качественную вещь')),
                ('price_high', models.IntegerField(verbose_name='Цена за дорогую вещь')),
                ('icon', models.ImageField(default='img/2015/08/04/ufo.jpg', upload_to='smiles/%Y/%m/%d/', verbose_name='Иконка набора смайликов')),
                ('smiles', models.ManyToManyField(to='inventory.Smile')),
            ],
        ),
        migrations.CreateModel(
            name='UserInventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Обычный предмет'), (2, 'Фон профиля'), (3, 'Набор смайликов')], verbose_name='Тип предмета')),
                ('item_id', models.IntegerField(verbose_name='Идентификатор предмета')),
                ('quality', models.IntegerField(choices=[(1, 'Низкое качество'), (2, 'Хорошее качество'), (3, 'Эксклюзивная вещь'), (4, 'Легендарное качество')], verbose_name='Качество предмета')),
                ('get_date', models.DateTimeField(auto_now=True, verbose_name='Дата получения предмета')),
                ('price', models.IntegerField(verbose_name='Цена за предмет')),
                ('stolen', models.BooleanField(default=False, verbose_name='Вещь уже продана')),
                ('no_stolen', models.BooleanField(default=False, verbose_name='Вещь нельзя продавать')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='distribution',
            name='items',
            field=models.ManyToManyField(to='inventory.UserInventoryItem'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catapult',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.UserInventoryItem'),
        ),
        migrations.AddField(
            model_name='catapult',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='getter', to=settings.AUTH_USER_MODEL),
        ),
    ]
