# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20160712_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название карточки')),
                ('icon', models.ImageField(upload_to='cards/', verbose_name='Обложка карточки')),
                ('description', models.TextField(blank=True, verbose_name='Описание карточки')),
                ('quality', models.IntegerField(choices=[(0, 'Обычная карта'), (1, 'Коллекционная карта'), (2, 'Уникальная карта'), (3, 'Золотая карта'), (4, 'Памятная карта')], verbose_name='Качество карточки')),
            ],
        ),
    ]
