# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название бустера')),
                ('icon', models.ImageField(blank=True, upload_to='boosters/', verbose_name='Название бустера')),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='quality',
            field=models.IntegerField(choices=[(0, 'Обычная карта'), (1, 'Коллекционная карта'), (2, 'Уникальная карта'), (3, 'Золотая карта'), (4, 'Памятная карта')], default=0, verbose_name='Качество карточки'),
        ),
        migrations.AddField(
            model_name='booster',
            name='cards',
            field=models.ManyToManyField(to='inventory.Card', verbose_name='Карточки'),
        ),
    ]
