# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 15:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.TextField(verbose_name='Местность')),
                ('resources', models.TextField(verbose_name='Карта ресурсов')),
                ('visible_map', models.TextField(verbose_name='Карта видимости')),
                ('buildings_map', models.TextField(verbose_name='Карта строений')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления информации')),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Карты',
                'verbose_name': 'Карта',
            },
        ),
    ]
