# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название здания')),
                ('pp', models.IntegerField(default=50, verbose_name='Количество очков производства')),
                ('icon', models.ImageField(blank=True, upload_to='game/buildings/', verbose_name='Иконка здания')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания',
            },
        ),
        migrations.CreateModel(
            name='BuildingBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Еда'), (2, 'Производство'), (3, 'Культура'), (4, 'Вера'), (5, 'Наука'), (6, 'Настроение'), (7, 'Туризм'), (8, 'Золото')], verbose_name='Тип бонуса')),
                ('value', models.IntegerField(default=0, verbose_name='Значение')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Building')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingBonusModificator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Еда'), (2, 'Производство'), (3, 'Культура'), (4, 'Вера'), (5, 'Наука'), (6, 'Настроение'), (7, 'Туризм'), (8, 'Золото')], verbose_name='Тип бонуса')),
                ('value', models.FloatField(default=0, verbose_name='Значение')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название технологии')),
                ('sp', models.IntegerField(default=50, verbose_name='Количество очков науки')),
                ('icon', models.ImageField(blank=True, upload_to='game/technologies/', verbose_name='Иконка технологии')),
            ],
            options={
                'verbose_name': 'Технология',
                'verbose_name_plural': 'Технологии',
            },
        ),
    ]
