# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20160701_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.CharField(max_length=128, verbose_name='Бонус технологии')),
            ],
        ),
        migrations.AddField(
            model_name='technology',
            name='buildings',
            field=models.ManyToManyField(to='game.Building', verbose_name='Здания'),
        ),
        migrations.AddField(
            model_name='technology',
            name='prev_technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Technology'),
        ),
        migrations.AddField(
            model_name='technologybonus',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Technology'),
        ),
    ]
