# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20160701_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название нации')),
                ('bonus', models.TextField(verbose_name='Бонус')),
            ],
        ),
        migrations.AlterField(
            model_name='technology',
            name='buildings',
            field=models.ManyToManyField(blank=True, to='game.Building', verbose_name='Здания'),
        ),
        migrations.AddField(
            model_name='building',
            name='nations',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='game.Nation'),
            preserve_default=False,
        ),
    ]
