# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20160701_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nation',
            options={'verbose_name': 'Нация', 'verbose_name_plural': 'Нации'},
        ),
        migrations.AddField(
            model_name='building',
            name='wonder',
            field=models.BooleanField(default=False, verbose_name='Чудо света'),
        ),
    ]
