# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20160702_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='nations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Nation'),
        ),
    ]
