# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20160702_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dogma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержимое догмата')),
                ('level', models.IntegerField(choices=[(1, 'Первый уровень'), (2, 'Второй уровень'), (3, 'Третий уровень')], default=1, verbose_name='Уровень догмата')),
            ],
        ),
    ]
