# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 14:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0010_auto_20160704_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.FloatField(blank=True, default=0, null=True, verbose_name='Прогресс постройки')),
                ('date_start', models.DateTimeField(verbose_name='Дата начала постройки')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания постройки')),
                ('completed', models.BooleanField(default=False, verbose_name='Технология изучена')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Building', verbose_name='Постройка')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Постройка игрока',
                'verbose_name_plural': 'Постройки игроков',
            },
        ),
        migrations.CreateModel(
            name='UserTeach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.FloatField(blank=True, default=0, null=True, verbose_name='Прогресс исследования')),
                ('date_start', models.DateTimeField(verbose_name='Дата начала изучения')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания изучения')),
                ('completed', models.BooleanField(default=False, verbose_name='Технология изучена')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Technology', verbose_name='Технология')),
            ],
            options={
                'verbose_name': 'Исследование игрока',
                'verbose_name_plural': 'Исследования игроков',
            },
        ),
    ]
