# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_userbuild_userteach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='prev_technology',
            new_name='next_technology',
        ),
    ]
