# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20160705_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='branch',
            field=models.IntegerField(blank=True, choices=[(1, 'Ветка культуры'), (2, 'Ветка производства'), (3, 'Ветка веры'), (4, 'Ветка еды'), (5, 'Ветка золота')], null=True, verbose_name='Ветвь исследования'),
        ),
    ]
