# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20160714_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbuild',
            name='x',
            field=models.IntegerField(default=1, verbose_name='Координата Х'),
        ),
        migrations.AddField(
            model_name='userbuild',
            name='y',
            field=models.IntegerField(default=1, verbose_name='Координата Х'),
        ),
    ]
