# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20160719_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
