# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_technology_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gmap',
            field=models.TextField(default='[]', verbose_name='Карта игры'),
        ),
    ]
