# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_game_gmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='sprite',
            field=models.CharField(blank=True, max_length=32, verbose_name='Имя спрайта'),
        ),
    ]
