# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_auto_20160802_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='castle_level',
            field=models.IntegerField(default=1, verbose_name='Уровень ратуши'),
        ),
        migrations.AddField(
            model_name='nation',
            name='icon',
            field=models.ImageField(blank=True, upload_to='game/flags/', verbose_name='Иконка здания'),
        ),
    ]
