# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 20:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0021_auto_20160805_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDogmat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата начала постройки')),
                ('dogmat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Dogma', verbose_name='Постройка')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='Игра')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Постройки игроков',
                'verbose_name': 'Постройка игрока',
            },
        ),
    ]
