# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_userdogmat'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='culture_level',
            field=models.IntegerField(default=0, verbose_name='Уровень культуры'),
        ),
    ]
