# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_game_culture_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(verbose_name='Позиция x')),
                ('y', models.IntegerField(verbose_name='Позиция y')),
                ('free', models.BooleanField(default=True, verbose_name='Безработность')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='Игра')),
            ],
        ),
    ]
