# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_citizen'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='citizens',
            field=models.IntegerField(default=0, verbose_name='Количество жителей'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='x',
            field=models.IntegerField(default=0, verbose_name='Позиция x'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='y',
            field=models.IntegerField(default=0, verbose_name='Позиция y'),
        ),
    ]
