# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_auto_20160813_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='tourist_count',
            field=models.IntegerField(default=0, verbose_name='Количество прибывших туристов'),
        ),
    ]
