# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_step_tourist_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdogmat',
            options={'verbose_name': 'Догмат игрока', 'verbose_name_plural': 'Догматы игроков'},
        ),
        migrations.AddField(
            model_name='game',
            name='teach_level',
            field=models.IntegerField(default=1, verbose_name='Уровень обучения'),
        ),
    ]
