# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_technology_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='price',
        ),
    ]
