# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_auto_20150819_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название предмета')),
                ('semester', models.IntegerField(choices=[(1, 'Первый семестр'), (2, 'Второй семестр'), (3, 'Третий семестр'), (4, 'Четвертый семестр'), (5, 'Пятый семестр'), (6, 'Шестой семестр'), (7, 'Седьмой семестр'), (8, 'Восьмой семестр')], default=1, verbose_name='Семестр')),
            ],
        ),
        migrations.AddField(
            model_name='timetable',
            name='group',
            field=models.IntegerField(choices=[(1, 'Общая пара'), (2, 'Первая подгруппа'), (3, 'Вторая подгруппа')], default=0, verbose_name='Подгруппа'),
        ),
        migrations.AlterField(
            model_name='control',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homework',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newplace',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Первый семестр'), (2, 'Второй семестр'), (3, 'Третий семестр'), (4, 'Четвертый семестр'), (5, 'Пятый семестр'), (6, 'Шестой семестр'), (7, 'Седьмой семестр'), (8, 'Восьмой семестр')], default=4, verbose_name='Семестр'),
        ),
    ]
