# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_timetable_earlier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='earlier',
            new_name='is_earlier',
        ),
    ]
