# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_auto_20160422_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='lessons',
            field=models.ManyToManyField(to='timetable.Lesson', verbose_name='Предметы, которые ведет этот преподаватель'),
        ),
    ]
