# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 14:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0015_auto_20160705_1704'),
        ('user', '0011_userprofile_last_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата предмета')),
                ('type', models.IntegerField(choices=[(1, 'Лекция'), (2, 'Практика'), (3, 'Лабораторная работа')], default=1, verbose_name='Тип занятия')),
                ('group', models.IntegerField(choices=[(0, 'Общее занятие'), (1, 'Первая подгруппа'), (2, 'Вторая подгруппа')], default=0, verbose_name='Подгруппа')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Lesson_Item')),
                ('visitor', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
            },
        ),
        migrations.CreateModel(
            name='BonusPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата получения')),
                ('bonus', models.IntegerField(verbose_name='Кол-во очков')),
                ('bingo', models.BooleanField(default=False, verbose_name='Случайный бонус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата предмета')),
                ('description', models.CharField(max_length=128, verbose_name='Описание долга')),
                ('group', models.IntegerField(choices=[(0, 'Общее занятие'), (1, 'Первая подгруппа'), (2, 'Вторая подгруппа')], default=0, verbose_name='Подгруппа')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Lesson_Item')),
                ('visitors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Долг',
                'verbose_name_plural': 'Долги',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accent',
            field=models.CharField(choices=[('red', 'Красный'), ('orange', 'Оранжевый'), ('yellow', 'Желтый'), ('olive', 'Оливковый'), ('green', 'Зеленый'), ('teal', 'Бирюзовый'), ('blue', 'Синий'), ('violet', 'Индиго'), ('purple', 'Фиолетовый'), ('pink', 'Пурпурный'), ('brown', 'Коричневый')], default='blue', max_length=12, verbose_name='Акцентный цвет'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='beta',
            field=models.BooleanField(default=False, verbose_name='Бета-функции'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bonus_points',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Бонусные очки'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='events_notification',
            field=models.BooleanField(default=True, verbose_name='Высылать уведомления о ближайших событиях'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='events_time_notification',
            field=models.IntegerField(choices=[(1, 'За 1 день до начала'), (2, 'За 2 дня до начала'), (3, 'За 3 дня до начала')], default=1, verbose_name='Уведомлять о событии'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='filter_achievements',
            field=models.BooleanField(default=True, verbose_name='Показывать записи о достижениях'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='filter_bonuses',
            field=models.BooleanField(default=True, verbose_name='Показывать записи о бонусах'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='filter_catapult',
            field=models.BooleanField(default=True, verbose_name='Показывать записи о запусках катапульты'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='filter_sales',
            field=models.BooleanField(default=True, verbose_name='Показывать записи о продажах'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Github'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.IntegerField(choices=[(1, 'Первая подгруппа'), (2, 'Вторая подгруппа')], default=1, verbose_name='Подгруппа'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hide_email',
            field=models.BooleanField(default=False, verbose_name='Скрывать адрес e-mail'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hide_tips',
            field=models.BooleanField(default=False, verbose_name='Скрывать подсказки'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lang',
            field=models.CharField(choices=[('ru', 'Русский язык'), ('en', 'Английский язык')], default='ru', max_length=2, verbose_name='Язык интерфейса'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notes_font_size',
            field=models.IntegerField(choices=[(14, '14px'), (16, '16px'), (18, '18px'), (20, '20px')], default=16, verbose_name='Размер шрифта в заметках'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notes_font_style',
            field=models.IntegerField(choices=[(1, 'Без засечек'), (2, 'С засечками')], default=1, verbose_name='Стиль шрифта в заметках'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notes_night_mode',
            field=models.BooleanField(default=False, verbose_name='Скрывать подсказки'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='polls_actual',
            field=models.BooleanField(default=True, verbose_name='Показывать актуальные темы'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('light', 'Светлая'), ('dark', 'Темная')], default='light', max_length=8, verbose_name='Тема'),
        ),
    ]
