# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20160712_2337'),
        ('user', '0012_auto_20160705_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='background',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.Background', verbose_name='Фоновый рисунок'),
        ),
    ]
