# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20160712_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='exp',
            field=models.IntegerField(default=0, verbose_name='Опыт'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Уровень'),
        ),
    ]
